Apply design
shockdayukio/proto-space pull request #4
Opened 2017-10-11 05:45 UTC by shockdayukio

# WHY
To build views

# WHAT
- Install gem 'bootstrap-sass'
- Import the design materials (haml, sass, image)

2017-10-11 09:16 UTC, offich requested changes
修正しくよろー

2017-10-11 09:16 UTC, r-ume commented on app/assets/stylesheets/application.css.scss
> +@import "protospace";
このファイルは、拡張子が `css.scss` になっているから、`scss` だけにしてくれるとー

2017-10-11 09:16 UTC, r-ume commented on app/assets/stylesheets/protospace.css.scss
> +/* -- import Roboto Font ------------------------------ */
このファイルもー

2017-10-11 09:16 UTC, r-ume commented on app/assets/stylesheets/stylesheets/application.css.scss
> +@import "bootstrap";
このファイルもー

2017-10-11 09:16 UTC, r-ume commented on app/assets/stylesheets/stylesheets/protospace.css.scss
> +/* -- import Roboto Font ------------------------------ */
これもー

2017-10-11 09:16 UTC, r-ume commented on app/views/views/layouts/_footer.html.haml
> +
空行してくれるとー。
sublimeの設定でできるよ。

2017-10-12 02:39 UTC, r-ume commented
まだ、全部、scssになっていないから、もう一度お願いしていい？

2017-10-12 11:55 UTC, r-ume commented
LGTM

2017-10-12 11:56 UTC, merged

2017-10-12 11:56 UTC, shockdayukio commented
thanks!!