[WIP]Install devise
shockdayukio/proto-space pull request #5
Opened 2017-10-13 06:37 UTC by shockdayukio

# WHY
Install gem 'devise'

#WHAT
- Install the gem 'devise'
- Install views that has been created 
- Create the User Model
- Create the Users Controller

2017-10-15 12:55 UTC, offich requested changes
コメントしたから、修正しくよろ〜

2017-10-15 12:55 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.text :profile
ここは、`null: false` のオプションをつけよう。

2017-10-15 12:55 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.string :name, null: false
ここは、`default: ''` を入れて、初期値を入れよう。

2017-10-15 12:55 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.string :avatar
ここは、`default: デフォルトの画像のパス`  を入れよう。

2017-10-15 12:55 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.string :works
ここも、`null: false`, `default: ''` を入れよう。

2017-10-15 12:55 UTC, r-ume commented on app/views/users/index.html.haml
> +      %a{"aria-label": "Previous", href: "#"}
GOOD
ハッシュロケットなくすのは、GOOD

2017-10-15 12:57 UTC, shockdayukio commented on app/views/users/index.html.haml
> +      %a{"aria-label": "Previous", href: "#"}
あざっす！

2017-10-16 06:44 UTC, offich requested changes
修正シクヨロ

2017-10-16 06:44 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.string :avatar, default: "noimage.png"
最後、ここに、`null: false` を入れるのお願いしてもいい？

2017-10-16 06:44 UTC, r-ume commented on db/migrate/20171013070328_devise_create_users.rb
> +      t.string :encrypted_password, null: false, default: ""
個人的にパスワードは、emailの下に来た方がいいかな。（これは、個人的な好みです。）

2017-10-16 09:04 UTC, r-ume commented
LGTM

2017-10-16 10:48 UTC, shockdayukio commented
Thank you!!

2017-10-16 10:48 UTC, merged