[WIP]Create a user's page in users#show
shockdayukio/proto-space pull request #6
Opened 2017-10-16 11:08 UTC by shockdayukio

# WHY
- To show all of user's information in one page 
#WHAT
- Create a routing to show action in the users controller
- Create the show action in the users controller
- Create a view in the users controller#show

2017-10-18 14:19 UTC, offich requested changes
修正しくよろー

2017-10-18 14:19 UTC, r-ume commented on app/controllers/prototypes_controller.rb
> +  before_action :authenticate_user!
仕様に従って、これは、indexアクションだけに当ててくれるとー

2017-10-18 14:19 UTC, r-ume commented on app/controllers/users_controller.rb
> +    @user.update(user_params)
updateに成功しなかった場合は、edit アクションに戻るようにしよう。

2017-10-18 14:19 UTC, r-ume commented on app/views/layouts/_header.html.haml
> +            =link_to current_user.name, "aria-expanded": "false", "data-toggle": "dropdown", href: "#", class: "dropdown-toggle" do
link_to があるから、`href:` はいらないね。

2017-10-21 01:39 UTC, offich reviewed
修正シクヨロ

2017-10-21 01:39 UTC, r-ume commented on app/controllers/prototypes_controller.rb
> +  before_action :authenticate_user!, only: :index
ごめん、間違えた... indexアクション以外にauthenticate_userをあてるだね...

2017-10-21 01:39 UTC, r-ume commented on app/controllers/users_controller.rb
> +    if user == true
これは、書き方が重複しているね。

2017-10-21 01:39 UTC, r-ume commented on app/views/users/edit.html.haml
> +              = f.file_field :avatar, value: @user.avatar
この辺は、今は修正しないけど、写真アップロード機能で修正しないといけないね。

2017-10-21 01:39 UTC, r-ume commented on app/views/users/show.html.haml
>          %a{href: "#"}
このaタグはいらないかな。

2017-10-21 07:48 UTC, shockdayukio commented on app/views/users/edit.html.haml
> +              = f.file_field :avatar, value: @user.avatar
OKです！

2017-10-21 07:54 UTC, shockdayukio commented on app/controllers/prototypes_controller.rb
> +  before_action :authenticate_user!, only: :index
仕様確認したんだけど、prototypesControllerってauthenticate_user! 当たってないかも。
ちょいと仕様確認してもらえると助かる！

ログインせずにアクセスしても、全部見れる
[http://proto-space.com/prototypes](http://proto-space.com/prototypes)
[http://proto-space.com/prototypes/2](http://proto-space.com/prototypes/2)
[http://proto-space.com/prototypes/new](http://proto-space.com/prototypes/new)

2017-10-21 11:59 UTC, r-ume commented on app/controllers/prototypes_controller.rb
> +  before_action :authenticate_user!, only: :index
仕様確認した！
けど、Webサービスとして、ログインせずに新規プロトタイプが作られるのは、なんか腑に落ちないから、indexとshowアクションに対しては、`authenticate_user` をつけなくても大丈夫。

2017-10-21 23:20 UTC, shockdayukio commented on app/controllers/prototypes_controller.rb
> +  before_action :authenticate_user!, only: :index
たしかに。りょうかいです！

2017-10-22 00:04 UTC, r-ume commented
LGTM

2017-10-22 00:33 UTC, merged